const InvitationActionTypes = {
  LIST_USER_INVITATIONS_START: "LIST_USER_INVITATIONS_START",
  LIST_USER_INVITATIONS_SUCCESS: "LIST_USER_INVITATIONS_SUCCESS",
  LIST_USER_INVITATIONS_FAILURE: "LIST_USER_INVITATIONS_FAILURE",
};

export default InvitationActionTypes;
