const InvitationActionTypes = {
  LIST_USER_INVITATIONS_START: "LIST_USER_INVITATIONS_START",
  LIST_USER_INVITATIONS_SUCCESS: "LIST_USER_INVITATIONS_SUCCESS",
  LIST_USER_INVITATIONS_FAILURE: "LIST_USER_INVITATIONS_FAILURE",
  ACCEPT_BAND_INVITATION_START: "ACCEPT_BAND_INVITATION_START",
  ACCEPT_BAND_INVITATION_SUCCESS: "ACCEPT_BAND_INVITATION_SUCCESS",
  ACCEPT_BAND_INVITATION_FAILURE: "ACCEPT_BAND_INVITATION_FAILURE",
};

export default InvitationActionTypes;
