const BandActionTypes = {
  CREATE_BAND_START: "CREATE_BAND_START",
  CREATE_BAND_SUCCESS: "CREATE_BAND_SUCCESS",
  CREATE_BAND_FAILURE: "CREATE_BAND_FAILURE",
  CREATE_INVITATION_START: "CREATE_INVITATION_START",
  CREATE_INVITATION_SUCCESS: "CREATE_INVITATION_SUCCESS",
  CREATE_INVITATION_FAILURE: "CREATE_INVITATION_FAILURE",
  UPLOAD_BAND_IMAGE_START: "UPLOAD_BAND_IMAGE_START",
  UPLOAD_BAND_IMAGE_SUCCESS: "UPLOAD_BAND_IMAGE_SUCCESS",
  UPLOAD_BAND_IMAGE_FAILURE: "UPLOAD_BAND_IMAGE_FAILURE",
  GET_BAND_IMAGE_START: "GET_BAND_IMAGE_START",
  GET_BAND_IMAGE_SUCCESS: "GET_BAND_IMAGE_SUCCESS",
  GET_BAND_IMAGE_FAILURE: "GET_BAND_IMAGE_FAILURE",
  LIST_BANDS_START: "LIST_BAND_START",
  LIST_BANDS_SUCCESS: "LIST_BAND_SUCCESS",
  LIST_BANDS_FAILURE: "LIST_BAND_FAILURE",
  UPDATE_BAND: "UPDATE_BAND",
  GET_BAND_START: "GET_BAND_START",
  GET_BAND_SUCCESS: "GET_BAND_SUCCESS",
  GET_BAND_FAILURE: "GET_BAND_FAILURE",
};

export default BandActionTypes;
