const BandActionTypes = {
  CREATE_BAND_START: "CREATE_BAND_START",
  CREATE_BAND_SUCCESS: "CREATE_BAND_SUCCESS",
  CREATE_BAND_FAILURE: "CREATE_BAND_FAILURE",
  CREATE_INVITATION_START: "CREATE_INVITATION_START",
  CREATE_INVITATION_SUCCESS: "CREATE_INVITATION_SUCCESS",
  CREATE_INVITATION_FAILURE: "CREATE_INVITATION_FAILURE",
  UPLOAD_BAND_IMAGE_START: "UPLOAD_BAND_IMAGE_START",
  UPLOAD_BAND_IMAGE_SUCCESS: "UPLOAD_BAND_IMAGE_SUCCESS",
  UPLOAD_BAND_IMAGE_FAILURE: "UPLOAD_BAND_IMAGE_FAILURE",
};

export default BandActionTypes;
