const BandActionTypes = {
  CREATE_BAND_START: "CREATE_BAND_START",
  CREATE_BAND_SUCCESS: "CREATE_BAND_SUCCESS",
  CREATE_BAND_FAILURE: "CREATE_BAND_FAILURE",
  CREATE_INVITATION_START: "CREATE_INVITATION_START",
  CREATE_INVITATION_SUCCESS: "CREATE_INVITATION_SUCCESS",
  CREATE_INVITATION_FAILURE: "CREATE_INVITATION_FAILURE",
};

export default BandActionTypes;
