const NotificationActionTypes = {
  CREATE_INVITE_NOTIFICATION_START: "CREATE_INVITE_NOTIFICATION_START",
  CREATE_INVITE_NOTIFICATION_SUCCESS: "CREATE_INVITE_NOTIFICATION_SUCCESS",
};

export default NotificationActionTypes;
