const TicketActionTypes = {
  CREATE_TICKET_START: "CREATE_TICKET_START",
  CREATE_TICKET_SUCCESS: "CREATE_TICKET_SUCCESS",
  CREATE_TICKET_FAILURE: "CREATE_TICKET_FAILURE",
  GET_TICKETS_BY_CONCERTID_START: "GET_TICKETS_BY_CONCERTID_START",
  GET_TICKETS_BY_CONCERTID_SUCCESS: "GET_TICKETS_BY_CONCERTID_SUCCESS",
  GET_TICKETS_BY_CONCERTID_FAILURE: "GET_TICKETS_BY_CONCERTID_FAILURE",
};

export default TicketActionTypes;
