const TicketActionTypes = {
  CREATE_TICKET_START: "CREATE_TICKET_START",
  CREATE_TICKET_SUCCESS: "CREATE_TICKET_SUCCESS",
  CREATE_TICKET_FAILURE: "CREATE_TICKET_FAILURE",
};

export default TicketActionTypes;
