const ConcertActionTypes = {
  CREATE_CONCERT_START: "CREATE_CONCERT_START",
  CREATE_CONCERT_SUCCESS: "CREATE_CONCERT_SUCCESS",
  CREATE_CONCERT_FAILURE: "CREATE_CONCERT_FAILURE",
  UPLOAD_CONCERT_IMAGE_START: "UPLOAD_CONCERT_IMAGE_START",
  UPLOAD_CONCERT_IMAGE_SUCCESS: "UPLOAD_CONCERT_IMAGE_SUCCESS",
  UPLOAD_CONCERT_IMAGE_FAILURE: "UPLOAD_CONCERT_IMAGE_FAILURE",
};

export default ConcertActionTypes;
