const ConcertActionTypes = {
  CREATE_CONCERT_START: "CREATE_CONCERT_START",
  CREATE_CONCERT_SUCCESS: "CREATE_CONCERT_SUCCESS",
  CREATE_CONCERT_FAILURE: "CREATE_CONCERT_FAILURE",
};

export default ConcertActionTypes;
