const ConcertActionTypes = {
  CREATE_CONCERT_START: "CREATE_CONCERT_START",
  CREATE_CONCERT_SUCCESS: "CREATE_CONCERT_SUCCESS",
  CREATE_CONCERT_FAILURE: "CREATE_CONCERT_FAILURE",
  UPLOAD_CONCERT_IMAGE_START: "UPLOAD_CONCERT_IMAGE_START",
  UPLOAD_CONCERT_IMAGE_SUCCESS: "UPLOAD_CONCERT_IMAGE_SUCCESS",
  UPLOAD_CONCERT_IMAGE_FAILURE: "UPLOAD_CONCERT_IMAGE_FAILURE",
  GET_CONCERT_IMAGE_START: "GET_CONCERT_IMAGE_START",
  GET_CONCERT_IMAGE_SUCCESS: "GET_CONCERT_IMAGE_SUCCESS",
  GET_CONCERT_IMAGE_FAILURE: "GET_CONCERT_IMAGE_FAILURE",
  CREATE_CONCERT_INVITATION_START: "CREATE_CONCERT_INVITATION_START",
  CREATE_CONCERT_INVITATION_SUCCESS: "CREATE_CONCERT_INVITATION_SUCCESS",
  CREATE_CONCERT_INVITATION_FAILURE: "CREATE_CONCERT_INVITATION_FAILURE",
  LIST_CONCERTS_START: "LIST_CONCERTS_START",
  LIST_CONCERTS_SUCCESS: "LIST_CONCERTS_SUCCESS",
  LIST_CONCERTS_FAILURE: "LIST_CONCERTS_FAILURE",
  GET_CONCERT_START: "GET_CONCERT_START",
  GET_CONCERT_SUCCESS: "GET_CONCERT_SUCCESS",
  GET_CONCERT_FAILURE: "GET_CONCERT_FAILURE",
  UPDATE_CONCERT: "UPDATE_CONCERT",
};

export default ConcertActionTypes;
