const OrderActionTypes = {
  CREATE_ORDER_START: "CREATE_ORDER_START",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILURE: "CREATE_ORDER_FAILURE",
  GET_ORDER_START: "GET_ORDER_START",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_FAILURE: "GET_ORDER_FAILURE",
  CLEAR_ORDER: "CLEAR_ORDER",
  PROCESS_PAYMENT_START: "PROCESS_PAYMENT_START",
  PROCESS_PAYMENT_SUCCESS: "PROCESS_PAYMENT_SUCCESS",
  PROCESS_PAYMENT_FAILURE: "PROCESS_PAYMENT_FAILURE",
  CLEAR_ORDER_RESPONSE: "CLEAR_ORDER_RESPONSE",
  LIST_USER_ORDERS_BY_DATE_START: "LIST_USER_ORDERS_BY_DATE_START",
  LIST_USER_ORDERS_BY_DATE_SUCCESS: "LIST_USER_ORDERS_BY_DATE_SUCCESS",
  LIST_USER_ORDERS_BY_DATE_FAILURE: "LIST_USER_ORDERS_BY_DATE_FAILURE",
  CLEAR_USER: "CLEAR_USER",
};

export default OrderActionTypes;
