const ArtistActionTypes = {
  CREATE_ARTIST_START: "CREATE_ARTIST_START",
  CREATE_ARTIST_SUCCESS: "CREATE_ARTIST_SUCCESS",
  CREATE_ARTIST_FAILURE: "CREATE_ARTIST_FAILURE",
  UPLOAD_ARTIST_IMAGE_START: "UPLOAD_ARTIST_IMAGE_START",
  UPLOAD_ARTIST_IMAGE_SUCCESS: "UPLOAD_ARTIST_IMAGE_SUCCESS",
  UPLOAD_ARTIST_IMAGE_FAILURE: "UPLOAD_ARTIST_IMAGE_FAILURE",
};

export default ArtistActionTypes;
