const ActionArtistTypes = {
  CREATE_ARTIST_START: "CREATE_ARTIST_START",
  CREATE_ARTIST_SUCCESS: "CREATE_ARTIST_SUCCESS",
  CREATE_ARTIST_FAILURE: "CREATE_ARTIST_FAILURE",
};

export default ActionArtistTypes;
